package view;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import model.Mdiagnosa;
import model.user;


public class diagnosadokter extends javax.swing.JFrame {
    
    public static String temp_no_diagnosa = "";
    DefaultComboBoxModel mdl = new DefaultComboBoxModel ();
    int IDDokter = user.getIDDokter();
    
    public diagnosadokter() {
        initComponents();
        Mdiagnosa.disable_field();
        TIdDokter.setVisible(false);
        Mdiagnosa.getDetailDokter();
        String [][] data = user.getProfilDokter(IDDokter);
        TIdDokter.setText(data[0][0]);
        TNamaDokter.setText(data [0][1]);
        Mdiagnosa.tabel();
        Mdiagnosa.hitungData();
        TNamaDokter.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LDataPemeriksaan = new javax.swing.JLabel();
        LNoDiagnosa = new javax.swing.JLabel();
        LIdDokter = new javax.swing.JLabel();
        LNamaPenyakit = new javax.swing.JLabel();
        LIdPasien = new javax.swing.JLabel();
        LNamaPasien = new javax.swing.JLabel();
        TNoDiagnosa = new javax.swing.JTextField();
        TNamaPasien = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelDataPemeriksaan = new javax.swing.JTable();
        TIdPasien = new javax.swing.JTextField();
        BCariPasien = new javax.swing.JButton();
        BTambah = new javax.swing.JButton();
        BSimpan = new javax.swing.JButton();
        BUbah = new javax.swing.JButton();
        BBatal = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        THasilPeriksa = new javax.swing.JTextArea();
        TIdDokter = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TJumlahData = new javax.swing.JLabel();
        TCariData = new javax.swing.JTextField();
        BCariData = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        TKeluhan = new javax.swing.JTextArea();
        TNamaDokter = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Sistem Informasi RS Pelita Harapan v1.0");
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 116, 25));

        LDataPemeriksaan.setFont(new java.awt.Font("Cambria", 1, 36)); // NOI18N
        LDataPemeriksaan.setForeground(new java.awt.Color(239, 239, 239));
        LDataPemeriksaan.setText("DATA PEMERIKSAAN");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(LDataPemeriksaan)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LDataPemeriksaan, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
        );

        LNoDiagnosa.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        LNoDiagnosa.setText("NO. DIAGNOSA            :");

        LIdDokter.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        LIdDokter.setText("NAMA DOKTER             :");

        LNamaPenyakit.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        LNamaPenyakit.setText("HASIL PERIKSA             :");

        LIdPasien.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        LIdPasien.setText("ID PASIEN                      :");

        LNamaPasien.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        LNamaPasien.setText("NAMA PASIEN              :");

        TNoDiagnosa.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        TNoDiagnosa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TNoDiagnosaActionPerformed(evt);
            }
        });

        TNamaPasien.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        TNamaPasien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TNamaPasienActionPerformed(evt);
            }
        });

        TabelDataPemeriksaan.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        TabelDataPemeriksaan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TabelDataPemeriksaan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelDataPemeriksaanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TabelDataPemeriksaan);

        TIdPasien.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        TIdPasien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TIdPasienActionPerformed(evt);
            }
        });

        BCariPasien.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        BCariPasien.setText("Cari");
        BCariPasien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCariPasienActionPerformed(evt);
            }
        });

        BTambah.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        BTambah.setText("Tambah");
        BTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTambahActionPerformed(evt);
            }
        });

        BSimpan.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        BSimpan.setText("Simpan");
        BSimpan.setEnabled(false);
        BSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BSimpanActionPerformed(evt);
            }
        });

        BUbah.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        BUbah.setText("Ubah");
        BUbah.setEnabled(false);
        BUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUbahActionPerformed(evt);
            }
        });

        BBatal.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        BBatal.setText("Batal");
        BBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BBatalActionPerformed(evt);
            }
        });

        THasilPeriksa.setColumns(20);
        THasilPeriksa.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        THasilPeriksa.setRows(5);
        THasilPeriksa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                THasilPeriksaKeyTyped(evt);
            }
        });
        jScrollPane2.setViewportView(THasilPeriksa);

        TIdDokter.setEditable(false);
        TIdDokter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TIdDokterActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 116, 25));

        jLabel1.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(243, 243, 243));
        jLabel1.setText("Jumlah Data      :");

        TJumlahData.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        TJumlahData.setForeground(new java.awt.Color(235, 235, 235));
        TJumlahData.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        TJumlahData.setText("00000");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TJumlahData, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                .addGap(11, 11, 11))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
            .addComponent(TJumlahData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        TCariData.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        TCariData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TCariDataActionPerformed(evt);
            }
        });

        BCariData.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        BCariData.setText("Cari");
        BCariData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCariDataActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel2.setText("KELUHAN                       :");

        TKeluhan.setColumns(20);
        TKeluhan.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        TKeluhan.setRows(5);
        TKeluhan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TKeluhanKeyTyped(evt);
            }
        });
        jScrollPane3.setViewportView(TKeluhan);

        TNamaDokter.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        TNamaDokter.setText("jTextField1");
        TNamaDokter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TNamaDokterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(LIdDokter)
                                            .addGap(18, 18, 18)
                                            .addComponent(TNamaDokter))
                                        .addComponent(LNamaPenyakit)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LNoDiagnosa)
                                .addGap(18, 18, 18)
                                .addComponent(TNoDiagnosa, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(TIdDokter, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LIdPasien)
                                .addGap(18, 18, 18)
                                .addComponent(TIdPasien, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BCariPasien))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LNamaPasien)
                                .addGap(18, 18, 18)
                                .addComponent(TNamaPasien)))
                        .addGap(48, 48, 48)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 602, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TCariData, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BCariData))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LNoDiagnosa)
                    .addComponent(TNoDiagnosa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TIdDokter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TCariData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BCariData))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 396, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LIdPasien)
                            .addComponent(TIdPasien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BCariPasien))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LNamaPasien)
                            .addComponent(TNamaPasien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LIdDokter)
                            .addComponent(TNamaDokter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(LNamaPenyakit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BTambah, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BSimpan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BUbah, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BBatal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(20, 20, 20))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TNoDiagnosaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TNoDiagnosaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TNoDiagnosaActionPerformed

    private void TNamaPasienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TNamaPasienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TNamaPasienActionPerformed

    private void BCariPasienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCariPasienActionPerformed
        // TODO add your handling code here:
        Mdiagnosa.FungsiCariPasien();
        Mdiagnosa.CekDataDobel();  
    }//GEN-LAST:event_BCariPasienActionPerformed

    private void BTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTambahActionPerformed
        // TODO add your handling code here:
        //CNamaDokter.setEnabled(true);
        Mdiagnosa.empty_field();
        Mdiagnosa.enable_field();
        Mdiagnosa.penomoran();
        Mdiagnosa.tabel();
        Mdiagnosa.hitungData();
        BTambah.setEnabled(false);
        BUbah.setEnabled(false);
        BSimpan.setEnabled(true);
    }//GEN-LAST:event_BTambahActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        Mdiagnosa.tabel();
//        Mdiagnosa.hitungData();
//        Mdiagnosa.empty_field();
//        String [] ListKategori = Mdiagnosa.getListIdDokter();
//        for (int i = 0; i < ListKategori.length; i++) {
//            mdl.addElement(ListKategori[i]);
//        }
//        CNamaDokter.setModel(mdl);
 //       CNamaDokter.setEditable(false);
    }//GEN-LAST:event_formComponentShown

    private void THasilPeriksaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_THasilPeriksaKeyTyped
        // TODO add your handling code here:
        THasilPeriksa.setLineWrap(true);
        THasilPeriksa.setWrapStyleWord(true);
    }//GEN-LAST:event_THasilPeriksaKeyTyped

    private void TabelDataPemeriksaanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelDataPemeriksaanMouseClicked
        // TODO add your handling code here:
        //CNamaDokter.setEnabled(true);
        TNoDiagnosa.setEditable(false);
        TKeluhan.setEditable(false);
        TNoDiagnosa.setText(TabelDataPemeriksaan.getValueAt(TabelDataPemeriksaan.getSelectedRow(), 0).toString());
        TNamaDokter.setText(TabelDataPemeriksaan.getValueAt(TabelDataPemeriksaan.getSelectedRow(), 1).toString());
        TNamaPasien.setText(TabelDataPemeriksaan.getValueAt(TabelDataPemeriksaan.getSelectedRow(), 2).toString());
        THasilPeriksa.setText(TabelDataPemeriksaan.getValueAt(TabelDataPemeriksaan.getSelectedRow(), 5).toString());
        TKeluhan.setText(TabelDataPemeriksaan.getValueAt(TabelDataPemeriksaan.getSelectedRow(), 4).toString());
        
        temp_no_diagnosa = TabelDataPemeriksaan.getValueAt(TabelDataPemeriksaan.getSelectedRow(), 0).toString();
        
        THasilPeriksa.setEditable(false);
        Mdiagnosa.getIdDokterUbah();
        TIdPasien.setEditable(false);
        TNamaPasien.setEditable(false);
        THasilPeriksa.setEditable(true);
        //CNamaDokter.requestFocus();
        BTambah.setEnabled(false);
        BSimpan.setEnabled(false);
        BUbah.setEnabled(true);
        BBatal.setEnabled(true);
        
    }//GEN-LAST:event_TabelDataPemeriksaanMouseClicked

    private void TIdPasienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TIdPasienActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_TIdPasienActionPerformed

    private void TIdDokterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TIdDokterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TIdDokterActionPerformed

    private void BSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BSimpanActionPerformed
        // TODO add your handling code here:
        if(TNoDiagnosa.getText().isEmpty() || TIdPasien.getText().isEmpty() || TNamaPasien.getText().isEmpty() || THasilPeriksa.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Ulangi, seluruh data harus diisi !");
                Mdiagnosa.HapusData();
                Mdiagnosa.empty_field();
                BTambah.setEnabled(false);
                Mdiagnosa.hitungData();
            }else{
                Mdiagnosa.SimpanData();
                Mdiagnosa.tabel();
                Mdiagnosa.empty_field();
                Mdiagnosa.hitungData();
                BTambah.setEnabled(true);
            }
        
        BTambah.setEnabled(true);
        BUbah.setEnabled(false);
        BSimpan.setEnabled(false);
        TNoDiagnosa.requestFocus();
    }//GEN-LAST:event_BSimpanActionPerformed

    private void BUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUbahActionPerformed
        // TODO add your handling code here:
        if(TNoDiagnosa.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Pilih Data Terlebih Dahulu !");
        }else if(TNoDiagnosa.getText().isEmpty() || TIdPasien.getText().isEmpty() || TNamaPasien.getText().isEmpty() || THasilPeriksa.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Ulangi, semua data harus diisi !");
        }else{
            Mdiagnosa.ubahData();           
            BTambah.setEnabled(true);
        }
        Mdiagnosa.hitungData();
        Mdiagnosa.tabel();
        Mdiagnosa.empty_field();
        BUbah.setEnabled(false);;
        BSimpan.setEnabled(false);
        TIdDokter.requestFocus();
    }//GEN-LAST:event_BUbahActionPerformed

    private void BBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BBatalActionPerformed
        // TODO add your handling code here:
        Mdiagnosa.getDetailDokter();
        String [][] data = user.getProfilDokter(IDDokter);
        TIdDokter.setText(data[0][0]);
        TNamaDokter.setText(data [0][1]);
        TNamaDokter.setEditable(false);
        Mdiagnosa.tabel();
        Mdiagnosa.hitungData();
        Mdiagnosa.disable_field();
        Mdiagnosa.empty_field();
        BTambah.setEnabled(true);
        BUbah.setEnabled(false);
        BSimpan.setEnabled(false);
    }//GEN-LAST:event_BBatalActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        ImageIcon icon = new ImageIcon("src/logo.png");
        setIconImage(icon.getImage());
    }//GEN-LAST:event_formWindowActivated

    private void BCariDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCariDataActionPerformed
        // TODO add your handling code here:
        Mdiagnosa.getDetailDokter();
        String [][] data = user.getProfilDokter(IDDokter);
        TIdDokter.setText(data[0][0]);
        TNamaDokter.setText(data[0][1]);
        if(TabelDataPemeriksaan.getRowCount()==0){
            JOptionPane.showMessageDialog(this, "Data tidak ditemukan");
        }
        Mdiagnosa.FungsiCari();
        Mdiagnosa.hitungData();
    }//GEN-LAST:event_BCariDataActionPerformed

    private void TCariDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TCariDataActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_TCariDataActionPerformed

    private void TKeluhanKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TKeluhanKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_TKeluhanKeyTyped

    private void TNamaDokterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TNamaDokterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TNamaDokterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(diagnosadokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(diagnosadokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(diagnosadokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(diagnosadokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new diagnosadokter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton BBatal;
    private javax.swing.JButton BCariData;
    public static javax.swing.JButton BCariPasien;
    private javax.swing.JButton BSimpan;
    private javax.swing.JButton BTambah;
    public static javax.swing.JButton BUbah;
    private javax.swing.JLabel LDataPemeriksaan;
    private javax.swing.JLabel LIdDokter;
    private javax.swing.JLabel LIdPasien;
    private javax.swing.JLabel LNamaPasien;
    private javax.swing.JLabel LNamaPenyakit;
    private javax.swing.JLabel LNoDiagnosa;
    public static javax.swing.JTextField TCariData;
    public static javax.swing.JTextArea THasilPeriksa;
    public static javax.swing.JTextField TIdDokter;
    public static javax.swing.JTextField TIdPasien;
    public static javax.swing.JLabel TJumlahData;
    public static javax.swing.JTextArea TKeluhan;
    public static javax.swing.JTextField TNamaDokter;
    public static javax.swing.JTextField TNamaPasien;
    public static javax.swing.JTextField TNoDiagnosa;
    public static javax.swing.JTable TabelDataPemeriksaan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
