package view;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import model.Mdokter;

public class dokter extends javax.swing.JFrame {
    
    public static String temp_id_dokter = "";

    public dokter() {
        initComponents();
        Mdokter.tabel();  
        Mdokter.hitungData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LDataDokter = new javax.swing.JLabel();
        LIdDokter = new javax.swing.JLabel();
        LNamaDokter = new javax.swing.JLabel();
        LSpesialis = new javax.swing.JLabel();
        LBiayaJasa = new javax.swing.JLabel();
        TIdDokter = new javax.swing.JTextField();
        TNamaDokter = new javax.swing.JTextField();
        TBiayaPeriksa = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelDataDokter = new javax.swing.JTable();
        BTambah = new javax.swing.JButton();
        BSimpan = new javax.swing.JButton();
        BUbah = new javax.swing.JButton();
        BHapus = new javax.swing.JButton();
        BBatal = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        TCari = new javax.swing.JTextField();
        TSpesialis = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        LJumlahData = new javax.swing.JLabel();
        LJumlahAngka = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Sistem Informasi RS Pelita Harapan v1.0");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 128, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(432, 92));

        LDataDokter.setFont(new java.awt.Font("Cambria", 1, 36)); // NOI18N
        LDataDokter.setForeground(new java.awt.Color(236, 236, 236));
        LDataDokter.setText("DATA DOKTER");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(LDataDokter)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LDataDokter, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
        );

        LIdDokter.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        LIdDokter.setText("ID DOKTER            :");

        LNamaDokter.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        LNamaDokter.setText("NAMA DOKTER    :");

        LSpesialis.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        LSpesialis.setText("SPESIALIS              :");

        LBiayaJasa.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        LBiayaJasa.setText("BIAYA PERIKSA   :");

        TIdDokter.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        TIdDokter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TIdDokterActionPerformed(evt);
            }
        });

        TNamaDokter.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        TNamaDokter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TNamaDokterActionPerformed(evt);
            }
        });

        TBiayaPeriksa.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        TBiayaPeriksa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TBiayaPeriksaActionPerformed(evt);
            }
        });

        TabelDataDokter.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        TabelDataDokter.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TabelDataDokter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelDataDokterMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TabelDataDokter);

        BTambah.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        BTambah.setText("Tambah");
        BTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTambahActionPerformed(evt);
            }
        });

        BSimpan.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        BSimpan.setText("Simpan");
        BSimpan.setEnabled(false);
        BSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BSimpanActionPerformed(evt);
            }
        });

        BUbah.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        BUbah.setText("Ubah");
        BUbah.setEnabled(false);
        BUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUbahActionPerformed(evt);
            }
        });

        BHapus.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        BHapus.setText("Hapus");
        BHapus.setEnabled(false);
        BHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BHapusActionPerformed(evt);
            }
        });

        BBatal.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        BBatal.setText("Batal");
        BBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BBatalActionPerformed(evt);
            }
        });

        jButton7.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jButton7.setText("Cari");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        TCari.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        TCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TCariActionPerformed(evt);
            }
        });

        TSpesialis.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        TSpesialis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TSpesialisActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 128, 0));

        LJumlahData.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        LJumlahData.setForeground(new java.awt.Color(233, 233, 233));
        LJumlahData.setText("Jumlah Data      :");

        LJumlahAngka.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        LJumlahAngka.setForeground(new java.awt.Color(236, 236, 236));
        LJumlahAngka.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LJumlahAngka.setText("00000");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(LJumlahData)
                .addGap(18, 18, 18)
                .addComponent(LJumlahAngka)
                .addGap(11, 11, 11))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LJumlahData, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
            .addComponent(LJumlahAngka, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 909, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(TCari, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton7))
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 771, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(228, 228, 228)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LBiayaJasa)
                                .addGap(18, 18, 18)
                                .addComponent(TBiayaPeriksa))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LNamaDokter)
                                .addGap(18, 18, 18)
                                .addComponent(TNamaDokter))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LIdDokter)
                                .addGap(18, 18, 18)
                                .addComponent(TIdDokter, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LSpesialis)
                                .addGap(18, 18, 18)
                                .addComponent(TSpesialis, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(BTambah)
                        .addGap(18, 18, 18)
                        .addComponent(BSimpan)
                        .addGap(18, 18, 18)
                        .addComponent(BUbah)
                        .addGap(18, 18, 18)
                        .addComponent(BHapus)
                        .addGap(18, 18, 18)
                        .addComponent(BBatal)))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LIdDokter)
                    .addComponent(TIdDokter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LNamaDokter)
                    .addComponent(TNamaDokter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBiayaJasa)
                    .addComponent(TBiayaPeriksa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LSpesialis)
                    .addComponent(TSpesialis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTambah)
                    .addComponent(BSimpan)
                    .addComponent(BUbah)
                    .addComponent(BHapus)
                    .addComponent(BBatal))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TIdDokterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TIdDokterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TIdDokterActionPerformed

    private void TNamaDokterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TNamaDokterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TNamaDokterActionPerformed

    private void TBiayaPeriksaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TBiayaPeriksaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TBiayaPeriksaActionPerformed

    private void TSpesialisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TSpesialisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TSpesialisActionPerformed

    private void BSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BSimpanActionPerformed
        // TODO add your handling code here:
        if(TIdDokter.getText().isEmpty() || TNamaDokter.getText().isEmpty() || TSpesialis.getText().isEmpty() || TBiayaPeriksa.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Ulangi, seluruh data harus diisi !");
                Mdokter.HapusData();
                Mdokter.empty_field();
                BTambah.setEnabled(false);
            }else{
                Mdokter.SimpanData();
                Mdokter.tabel();
                JOptionPane.showMessageDialog(this, "Data Disimpan !");
                Mdokter.empty_field();
                BTambah.setEnabled(true);
            }
        BTambah.setEnabled(true);
        BUbah.setEnabled(false);
        BHapus.setEnabled(false);
        BSimpan.setEnabled(false);
        TIdDokter.requestFocus();
        Mdokter.hitungData();
    }//GEN-LAST:event_BSimpanActionPerformed

    private void TabelDataDokterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelDataDokterMouseClicked
        // TODO add your handling code here:
        TIdDokter.setText(TabelDataDokter.getValueAt(TabelDataDokter.getSelectedRow(), 0).toString());
        TNamaDokter.setText(TabelDataDokter.getValueAt(TabelDataDokter.getSelectedRow(), 1).toString());
        TSpesialis.setText(TabelDataDokter.getValueAt(TabelDataDokter.getSelectedRow(), 2).toString());
        TBiayaPeriksa.setText(TabelDataDokter.getValueAt(TabelDataDokter.getSelectedRow(), 3).toString());
        
        temp_id_dokter = TabelDataDokter.getValueAt(TabelDataDokter.getSelectedRow(), 0).toString();
        
        TIdDokter.setEditable(false);
        BTambah.setEnabled(false);
        BSimpan.setEnabled(false);
        BUbah.setEnabled(true);
        BHapus.setEnabled(true);
    }//GEN-LAST:event_TabelDataDokterMouseClicked

    private void BTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTambahActionPerformed
        // TODO add your handling code here:
        Mdokter.empty_field();
        Mdokter.enable_field();
        Mdokter.penomoran();
        Mdokter.tabel();
        BTambah.setEnabled(false);
        BUbah.setEnabled(false);
        BHapus.setEnabled(false);
        BSimpan.setEnabled(true);
        TIdDokter.requestFocus();
        TIdDokter.setEditable(false);
        Mdokter.hitungData();
    }//GEN-LAST:event_BTambahActionPerformed

    private void BUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUbahActionPerformed
        // TODO add your handling code here:
        if(TIdDokter.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Pilih Data Terlebih Dahulu !");
        }else if(TIdDokter.getText().isEmpty() || TNamaDokter.getText().isEmpty() || TSpesialis.getText().isEmpty() || TBiayaPeriksa.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Ulangi, semua data harus diisi !");
        }else{
            Mdokter.UbahData();
            JOptionPane.showMessageDialog(this, "Data berhasil diubah");
        }
        Mdokter.hitungData();
        Mdokter.tabel();
        Mdokter.empty_field();
        BUbah.setEnabled(true);
        BTambah.setEnabled(false);
        BHapus.setEnabled(false);
        BSimpan.setEnabled(false);
        TIdDokter.requestFocus();                                     
    }//GEN-LAST:event_BUbahActionPerformed

    private void BHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BHapusActionPerformed
        // TODO add your handling code here:
        if(TIdDokter.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Pilih data terlebih dahulu !");            
        }else{
            int reply = JOptionPane.showConfirmDialog(this,"Hapus data dokter ?","Peringatan", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
            if (reply == JOptionPane.YES_OPTION){
                Mdokter.HapusData();
                JOptionPane.showMessageDialog(this, "Data dokter berhasil dihapus");
                Mdokter.tabel();
            }else{
                JOptionPane.showMessageDialog(this, "Batal menghapus data ini");
            }
        }
        Mdokter.hitungData();
        Mdokter.empty_field();
    }//GEN-LAST:event_BHapusActionPerformed

    private void BBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BBatalActionPerformed
        // TODO add your handling code here:
        Mdokter.tabel();
        Mdokter.hitungData();
        Mdokter.disable_field();
        Mdokter.empty_field();
        BTambah.setEnabled(true);
        BUbah.setEnabled(false);
        BHapus.setEnabled(false);
        BSimpan.setEnabled(false);
    }//GEN-LAST:event_BBatalActionPerformed

    private void TCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TCariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TCariActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:     
        if(TabelDataDokter.getRowCount()==0){
            JOptionPane.showMessageDialog(this, "Data tidak ditemukan");
        }
        Mdokter.FungsiCari();
        Mdokter.hitungData();
        TCari.requestFocus();
        
    }//GEN-LAST:event_jButton7ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        ImageIcon icon = new ImageIcon("src/logo.png");
        setIconImage(icon.getImage());
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dokter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BBatal;
    private javax.swing.JButton BHapus;
    private javax.swing.JButton BSimpan;
    private javax.swing.JButton BTambah;
    private javax.swing.JButton BUbah;
    private javax.swing.JLabel LBiayaJasa;
    private javax.swing.JLabel LDataDokter;
    private javax.swing.JLabel LIdDokter;
    public static javax.swing.JLabel LJumlahAngka;
    private javax.swing.JLabel LJumlahData;
    private javax.swing.JLabel LNamaDokter;
    private javax.swing.JLabel LSpesialis;
    public static javax.swing.JTextField TBiayaPeriksa;
    public static javax.swing.JTextField TCari;
    public static javax.swing.JTextField TIdDokter;
    public static javax.swing.JTextField TNamaDokter;
    public static javax.swing.JTextField TSpesialis;
    public static javax.swing.JTable TabelDataDokter;
    private javax.swing.JButton jButton7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
