/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import model.Mobat;

/**
 *
 * @author HP
 */
public class obat extends javax.swing.JFrame {
    
    public static String temp_no_obat = "";

    /**
     * Creates new form obat
     */
    public obat() {
        initComponents();
        Mobat.tabel();
        Mobat.hitungData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LObat = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        LNamaObat = new javax.swing.JLabel();
        LJenisObat = new javax.swing.JLabel();
        LDosis = new javax.swing.JLabel();
        LHarga = new javax.swing.JLabel();
        TNoObat = new javax.swing.JTextField();
        TNamaObat = new javax.swing.JTextField();
        TJenisObat = new javax.swing.JTextField();
        THarga = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelObat = new javax.swing.JTable();
        BTambah = new javax.swing.JButton();
        BSimpan = new javax.swing.JButton();
        BUbah = new javax.swing.JButton();
        BHapus = new javax.swing.JButton();
        BBatal = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TDosis = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TJumlah = new javax.swing.JLabel();
        TCariObat = new javax.swing.JTextField();
        BCari = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Sistem Informasi RS Pelita Harapan v1.0");
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 128, 0));

        LObat.setFont(new java.awt.Font("Cambria", 1, 36)); // NOI18N
        LObat.setForeground(new java.awt.Color(233, 233, 233));
        LObat.setText("OBAT");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(LObat)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LObat, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
        );

        jLabel2.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel2.setText("NO. OBAT                :");

        LNamaObat.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        LNamaObat.setText("NAMA OBAT          :");

        LJenisObat.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        LJenisObat.setText("JENIS OBAT            :");

        LDosis.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        LDosis.setText(" DOSIS                       :");

        LHarga.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        LHarga.setText("HARGA (Rp)             :");

        TNoObat.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        TNoObat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TNoObatActionPerformed(evt);
            }
        });

        TNamaObat.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        TNamaObat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TNamaObatActionPerformed(evt);
            }
        });

        TJenisObat.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        TJenisObat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TJenisObatActionPerformed(evt);
            }
        });

        THarga.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        THarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                THargaActionPerformed(evt);
            }
        });

        TabelObat.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        TabelObat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TabelObat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelObatMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TabelObat);

        BTambah.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        BTambah.setText("Tambah");
        BTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTambahActionPerformed(evt);
            }
        });

        BSimpan.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        BSimpan.setText("Simpan");
        BSimpan.setEnabled(false);
        BSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BSimpanActionPerformed(evt);
            }
        });

        BUbah.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        BUbah.setText("Ubah");
        BUbah.setEnabled(false);
        BUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUbahActionPerformed(evt);
            }
        });

        BHapus.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        BHapus.setText("Hapus");
        BHapus.setEnabled(false);
        BHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BHapusActionPerformed(evt);
            }
        });

        BBatal.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        BBatal.setText("Batal");
        BBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BBatalActionPerformed(evt);
            }
        });

        TDosis.setColumns(20);
        TDosis.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        TDosis.setRows(5);
        TDosis.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TDosisKeyTyped(evt);
            }
        });
        jScrollPane2.setViewportView(TDosis);

        jPanel2.setBackground(new java.awt.Color(0, 128, 0));

        jLabel1.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(238, 238, 238));
        jLabel1.setText("Jumlah Data       :");

        TJumlah.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        TJumlah.setForeground(new java.awt.Color(233, 233, 233));
        TJumlah.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        TJumlah.setText("000000");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TJumlah, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        TCariObat.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        TCariObat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TCariObatActionPerformed(evt);
            }
        });

        BCari.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        BCari.setText("Cari");
        BCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCariActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(LHarga)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(THarga)
                        .addGap(177, 177, 177))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(LNamaObat)
                                    .addComponent(LJenisObat)
                                    .addComponent(LDosis))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TNamaObat, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TNoObat, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(TJenisObat, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BTambah)
                                .addGap(18, 18, 18)
                                .addComponent(BSimpan)
                                .addGap(18, 18, 18)
                                .addComponent(BUbah)
                                .addGap(18, 18, 18)
                                .addComponent(BHapus)
                                .addGap(18, 18, 18)
                                .addComponent(BBatal)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 679, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(TCariObat, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BCari)
                        .addGap(64, 64, 64))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TNoObat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TCariObat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BCari))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LNamaObat)
                            .addComponent(TNamaObat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LJenisObat)
                            .addComponent(TJenisObat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LDosis)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LHarga)
                            .addComponent(THarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BTambah)
                            .addComponent(BSimpan)
                            .addComponent(BUbah)
                            .addComponent(BHapus)
                            .addComponent(BBatal)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUbahActionPerformed
        // TODO add your handling code here:
        if(TNoObat.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Pilih Data Terlebih Dahulu !");
        }else if(TNoObat.getText().isEmpty() || TNamaObat.getText().isEmpty() || TJenisObat.getText().isEmpty() || TDosis.getText().isEmpty() || THarga.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Ulangi, semua data harus diisi !");
        }else{
            Mobat.UbahData();
            JOptionPane.showMessageDialog(null, "Data berhasil diubah","Update Data",JOptionPane.INFORMATION_MESSAGE);
            BTambah.setEnabled(true);
        }
        //Mdiagnosa.hitungData();
        TabelObat.requestFocus();
        Mobat.tabel();
        Mobat.empty_field();
        BUbah.setEnabled(false);;
        BHapus.setEnabled(false);
        BSimpan.setEnabled(false);
    }//GEN-LAST:event_BUbahActionPerformed

    private void TNoObatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TNoObatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TNoObatActionPerformed

    private void TNamaObatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TNamaObatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TNamaObatActionPerformed

    private void TJenisObatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TJenisObatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TJenisObatActionPerformed

    private void THargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_THargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_THargaActionPerformed

    private void TabelObatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelObatMouseClicked
        // TODO add your handling code here:
        TNoObat.setText(TabelObat.getValueAt(TabelObat.getSelectedRow(), 0).toString());
        TNamaObat.setText(TabelObat.getValueAt(TabelObat.getSelectedRow(), 1).toString());
        TJenisObat.setText(TabelObat.getValueAt(TabelObat.getSelectedRow(), 2).toString());
        TDosis.setText(TabelObat.getValueAt(TabelObat.getSelectedRow(), 3).toString());
        THarga.setText(TabelObat.getValueAt(TabelObat.getSelectedRow(), 4).toString());
        
        temp_no_obat = TabelObat.getValueAt(TabelObat.getSelectedRow(), 0).toString();
        
        TNoObat.setEditable(false);
        TNamaObat.setEditable(true);
        TDosis.setEditable(true);
        TJenisObat.setEditable(true);
        THarga.setEditable(true);
        BTambah.setEnabled(false);
        BSimpan.setEnabled(false);
        BUbah.setEnabled(true);
        BHapus.setEnabled(true);
    }//GEN-LAST:event_TabelObatMouseClicked

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_formComponentShown

    private void BTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTambahActionPerformed
        // TODO add your handling code here:
        Mobat.empty_field();
        Mobat.enable_field();
        Mobat.penomoran();
        Mobat.tabel(); 
        Mobat.hitungData();
        BTambah.setEnabled(false);
        BUbah.setEnabled(false);
        BHapus.setEnabled(false);
        BSimpan.setEnabled(true);
    }//GEN-LAST:event_BTambahActionPerformed

    private void BSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BSimpanActionPerformed
        // TODO add your handling code here:
        if(TNoObat.getText().isEmpty() || TNamaObat.getText().isEmpty() || TJenisObat.getText().isEmpty() || TDosis.getText().isEmpty() || THarga.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Ulangi, seluruh data harus diisi !");
                Mobat.HapusData();
                Mobat.empty_field();
                BTambah.setEnabled(false);
                Mobat.hitungData();
            }else{
                Mobat.SimpanData();
                JOptionPane.showMessageDialog(null, "Data berhasil disimpan","Insert Data",JOptionPane.INFORMATION_MESSAGE);
                Mobat.tabel();
                Mobat.empty_field();
                Mobat.hitungData();
                BTambah.setEnabled(true);
            }
        BTambah.setEnabled(true);
        BUbah.setEnabled(false);
        BHapus.setEnabled(false);
        BSimpan.setEnabled(false);
        TNoObat.requestFocus();
    }//GEN-LAST:event_BSimpanActionPerformed

    private void TDosisKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TDosisKeyTyped
    // TODO add your handling code here:
    }//GEN-LAST:event_TDosisKeyTyped

    private void BHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BHapusActionPerformed
        // TODO add your handling code here:
        if(TNoObat.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Pilih data terlebih dahulu !");            
        }else{
            int reply = JOptionPane.showConfirmDialog(this,"Hapus data ?","Peringatan", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
            if (reply == JOptionPane.YES_OPTION){
                Mobat.HapusData();
                Mobat.tabel();
                Mobat.hitungData();
            }else{
                JOptionPane.showMessageDialog(this, "Batal menghapus data ini");
            }
        }
        Mobat.empty_field();                                    
    }//GEN-LAST:event_BHapusActionPerformed

    private void BBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BBatalActionPerformed
        // TODO add your handling code here:
        Mobat.tabel();
        Mobat.disable_field();
        Mobat.empty_field();
        BTambah.setEnabled(true);
        BUbah.setEnabled(false);
        BHapus.setEnabled(false);
        BSimpan.setEnabled(false);
    }//GEN-LAST:event_BBatalActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        ImageIcon icon = new ImageIcon("src/logo.png");
        setIconImage(icon.getImage());
    }//GEN-LAST:event_formWindowActivated

    private void TCariObatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TCariObatActionPerformed
        // TODO add your handling code here:
                
    }//GEN-LAST:event_TCariObatActionPerformed

    private void BCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCariActionPerformed
        // TODO add your handling code here:
        if(TabelObat.getRowCount()==0){
            JOptionPane.showMessageDialog(this, "Data tidak ditemukan");
            Mobat.empty_field();
        }
        Mobat.FungsiCari();
        Mobat.hitungData();
    }//GEN-LAST:event_BCariActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(obat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(obat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(obat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(obat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new obat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton BBatal;
    public static javax.swing.JButton BCari;
    public static javax.swing.JButton BHapus;
    public static javax.swing.JButton BSimpan;
    public static javax.swing.JButton BTambah;
    public static javax.swing.JButton BUbah;
    private javax.swing.JLabel LDosis;
    private javax.swing.JLabel LHarga;
    private javax.swing.JLabel LJenisObat;
    private javax.swing.JLabel LNamaObat;
    private javax.swing.JLabel LObat;
    public static javax.swing.JTextField TCariObat;
    public static javax.swing.JTextArea TDosis;
    public static javax.swing.JTextField THarga;
    public static javax.swing.JTextField TJenisObat;
    public static javax.swing.JLabel TJumlah;
    public static javax.swing.JTextField TNamaObat;
    public static javax.swing.JTextField TNoObat;
    public static javax.swing.JTable TabelObat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
