package view;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import model.Mresep;
import model.user;

public class resepdokter extends javax.swing.JFrame {
    
    int IDDokter = user.getIDDokter();
    public static String temp_no_resep = "";
    DefaultComboBoxModel mdl = new DefaultComboBoxModel ();
    java.text.SimpleDateFormat kal = new java.text.SimpleDateFormat("yyyy-MM-dd");

    /**
     * Creates new form resep
     */
    public resepdokter() {
        initComponents();
        TNoObat.setVisible(false);
        BCari.setVisible(false);
        TTabelResep.requestFocus();
        String [][] data = user.getProfilDokter(IDDokter);
        TIdDokter.setText(data[0][0]);
        TNamaDokter.setText(data[0][1]);
        Mresep.tabel();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LResep = new javax.swing.JLabel();
        LNoResep = new javax.swing.JLabel();
        LIdPasien = new javax.swing.JLabel();
        LNamaPasien = new javax.swing.JLabel();
        LTanggal = new javax.swing.JLabel();
        TNoResep = new javax.swing.JTextField();
        TNamaPasien = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TTabelResep = new javax.swing.JTable();
        BUbah = new javax.swing.JButton();
        BBatal = new javax.swing.JButton();
        TIdPasien = new javax.swing.JTextField();
        BCari = new javax.swing.JButton();
        LHasilPeriksa = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        THasilPeriksa = new javax.swing.JTextArea();
        LObat = new javax.swing.JLabel();
        CObat = new javax.swing.JComboBox<>();
        TNoObat = new javax.swing.JTextField();
        TTanggal = new com.toedter.calendar.JDateChooser();
        TIdDokter = new javax.swing.JLabel();
        TNamaDokter = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Sistem Informasi RS Pelita Harapan v1.0");
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 116, 25));

        LResep.setFont(new java.awt.Font("Cambria", 1, 36)); // NOI18N
        LResep.setForeground(new java.awt.Color(235, 235, 235));
        LResep.setText("RESEP");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(LResep)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LResep, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        LNoResep.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        LNoResep.setText("NO. RESEP                           :");

        LIdPasien.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        LIdPasien.setText("ID PASIEN                           :");

        LNamaPasien.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        LNamaPasien.setText("NAMA PASIEN                  :");

        LTanggal.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        LTanggal.setText("TANGGAL  RESEP                    :");

        TNoResep.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        TNoResep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TNoResepActionPerformed(evt);
            }
        });

        TNamaPasien.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        TNamaPasien.setToolTipText("");
        TNamaPasien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TNamaPasienActionPerformed(evt);
            }
        });

        TTabelResep.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        TTabelResep.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TTabelResep.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TTabelResepMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TTabelResep);

        BUbah.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        BUbah.setText("Simpan");
        BUbah.setEnabled(false);
        BUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUbahActionPerformed(evt);
            }
        });

        BBatal.setFont(new java.awt.Font("Cambria", 0, 24)); // NOI18N
        BBatal.setText("Batal");
        BBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BBatalActionPerformed(evt);
            }
        });

        TIdPasien.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        TIdPasien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TIdPasienActionPerformed(evt);
            }
        });

        BCari.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        BCari.setText("Cari");
        BCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCariActionPerformed(evt);
            }
        });

        LHasilPeriksa.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        LHasilPeriksa.setText("HASIL PEMERIKSAAN          :");

        THasilPeriksa.setColumns(20);
        THasilPeriksa.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        THasilPeriksa.setRows(5);
        THasilPeriksa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                THasilPeriksaKeyTyped(evt);
            }
        });
        jScrollPane2.setViewportView(THasilPeriksa);

        LObat.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        LObat.setText(" RESEPKAN OBAT            :");

        CObat.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        CObat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        CObat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CObatActionPerformed(evt);
            }
        });

        TNoObat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TNoObatActionPerformed(evt);
            }
        });

        TTanggal.setDateFormatString("yyyy-MM-dd");
        TTanggal.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N

        TIdDokter.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        TIdDokter.setText("jLabel1");
        TIdDokter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TIdDokterMouseEntered(evt);
            }
        });

        TNamaDokter.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        TNamaDokter.setText("jLabel1");
        TNamaDokter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TNamaDokterMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(480, 480, 480)
                                .addComponent(LTanggal)
                                .addGap(18, 18, 18)
                                .addComponent(TTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(297, 297, 297)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(182, 182, 182)
                                        .addComponent(BBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(LNoResep)
                                            .addComponent(LIdPasien))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(TNoResep, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TIdPasien, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(29, 29, 29)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(BCari)
                                            .addComponent(TNoObat, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(2, 2, 2)
                                                .addComponent(LNamaPasien))
                                            .addComponent(LObat))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(CObat, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TNamaPasien, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(LHasilPeriksa)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 27, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(TIdDokter)
                                        .addGap(18, 18, 18)
                                        .addComponent(TNamaDokter))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 925, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(51, 51, 51))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TIdDokter)
                    .addComponent(TNamaDokter))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LHasilPeriksa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2)
                                .addGap(23, 23, 23)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LTanggal)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TNoResep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LNoResep)
                            .addComponent(TNoObat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LIdPasien)
                            .addComponent(TIdPasien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BCari))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LNamaPasien)
                            .addComponent(TNamaPasien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LObat)
                            .addComponent(CObat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BUbah, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                    .addComponent(BBatal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TNoResepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TNoResepActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_TNoResepActionPerformed

    private void BCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCariActionPerformed
        // TODO add your handling code here:
        Mresep.FungsiCariPasien();
        Mresep.CekDataDobel();
    }//GEN-LAST:event_BCariActionPerformed

    private void TTabelResepMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TTabelResepMouseClicked
        // TODO add your handling code here:
        
        TNoResep.setText(TTabelResep.getValueAt(TTabelResep.getSelectedRow(), 0).toString());
        java.util.Date tgl_resep=null;
        try{
        tgl_resep = new SimpleDateFormat("yyyy-MM-dd").parse(TTabelResep.getValueAt(TTabelResep.getSelectedRow(), 5).toString());
        }catch(ParseException ex){
            System.out.println(ex);
        }
        TTanggal.setDate(tgl_resep);
        TNamaPasien.setText(TTabelResep.getValueAt(TTabelResep.getSelectedRow(), 2).toString());
        THasilPeriksa.setText(TTabelResep.getValueAt(TTabelResep.getSelectedRow(), 3).toString());
        CObat.setSelectedItem(TTabelResep.getValueAt(TTabelResep.getSelectedRow(), 4).toString());
        
        temp_no_resep = TTabelResep.getValueAt(TTabelResep.getSelectedRow(), 0).toString();
        
        Mresep.getIdPasien();
        THasilPeriksa.setEditable(false);
        BCari.setEnabled(false);
        TIdPasien.setEditable(false);
        TNoResep.setEditable(false);
        BUbah.setEnabled(true);
        TNamaPasien.setEditable(false);
        BBatal.setEnabled(true);
        
    }//GEN-LAST:event_TTabelResepMouseClicked

    private void BUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUbahActionPerformed
        // TODO add your handling code here:
        if(TNoResep.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Pilih Data Terlebih Dahulu !");
        }else if(TNoResep.getText().isEmpty() || TIdPasien.getText().isEmpty() || TNamaPasien.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Ulangi, semua data harus diisi !");
        }else{
            Mresep.ubahData();

        }
        TTanggal.requestFocus();
        Mresep.tabel();
        Mresep.empty_field();
        BUbah.setEnabled(false);;
    }//GEN-LAST:event_BUbahActionPerformed

    private void BBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BBatalActionPerformed
        // TODO add your handling code here:
        Mresep.tabel();
        Mresep.disable_field();
        Mresep.empty_field();
        TTanggal.setDate(null);
        CObat.setSelectedItem("-");
        BUbah.setEnabled(false);
    }//GEN-LAST:event_BBatalActionPerformed

    private void TIdPasienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TIdPasienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TIdPasienActionPerformed

    private void TNamaPasienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TNamaPasienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TNamaPasienActionPerformed

    private void THasilPeriksaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_THasilPeriksaKeyTyped
        // TODO add your handling code here:
        
    }//GEN-LAST:event_THasilPeriksaKeyTyped

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        Mresep.empty_field();
        String [] ListKategori = Mresep.getListObat();
        for (int i = 0; i < ListKategori.length; i++) {
            mdl.addElement(ListKategori[i]);
        }
        CObat.setModel(mdl);
        CObat.setEditable(false);
    }//GEN-LAST:event_formComponentShown

    private void TNoObatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TNoObatActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_TNoObatActionPerformed

    private void CObatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CObatActionPerformed
        // TODO add your handling code here:
        Mresep.getNoObat();
    }//GEN-LAST:event_CObatActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        ImageIcon icon = new ImageIcon("src/logo.png");
        setIconImage(icon.getImage());
    }//GEN-LAST:event_formWindowActivated

    private void TIdDokterMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TIdDokterMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_TIdDokterMouseEntered

    private void TNamaDokterMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TNamaDokterMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_TNamaDokterMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(resepdokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(resepdokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(resepdokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(resepdokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new resepdokter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton BBatal;
    public static javax.swing.JButton BCari;
    public static javax.swing.JButton BUbah;
    public static javax.swing.JComboBox<String> CObat;
    private javax.swing.JLabel LHasilPeriksa;
    private javax.swing.JLabel LIdPasien;
    private javax.swing.JLabel LNamaPasien;
    private javax.swing.JLabel LNoResep;
    private javax.swing.JLabel LObat;
    private javax.swing.JLabel LResep;
    private javax.swing.JLabel LTanggal;
    public static javax.swing.JTextArea THasilPeriksa;
    public static javax.swing.JLabel TIdDokter;
    public static javax.swing.JTextField TIdPasien;
    public static javax.swing.JLabel TNamaDokter;
    public static javax.swing.JTextField TNamaPasien;
    public static javax.swing.JTextField TNoObat;
    public static javax.swing.JTextField TNoResep;
    public static javax.swing.JTable TTabelResep;
    public static com.toedter.calendar.JDateChooser TTanggal;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
